const BOOKS_WITH_TAGS = [
  {
    title: "The Shining 1",
    img: "/assets/images/cover_the_shining.webp",
    status: "Completed",
    rating: "4.5",
    genre: ["Action", "Fantasy"],
    desc: "Jack Torrance (Jack Nicholson) becomes winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. He settles in along with his wife, Wendy (Shelley Duvall), and his son, Danny (Danny Lloyd), who is plagued by psychic premonitions. As Jack's writing goes nowhere and Danny's visions become more disturbing, Jack discovers the hotel's dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.",
  },
  {
    title: "The Shining 2",
    img: "/assets/images/cover_the_shining.webp",
    status: "Ongoing",
    rating: "3.2",
    genre: ["Horror", "Mystery"],
    desc: "Jack Torrance (Jack Nicholson) becomes winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. He settles in along with his wife, Wendy (Shelley Duvall), and his son, Danny (Danny Lloyd), who is plagued by psychic premonitions. As Jack's writing goes nowhere and Danny's visions become more disturbing, Jack discovers the hotel's dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.",
  },
  {
    title: "The Shining 3",
    img: "/assets/images/cover_the_shining.webp",
    status: "Haitus",
    rating: "4.7",
    genre: ["Sci Fi", "Dystopian"],
    desc: "Jack Torrance (Jack Nicholson) becomes winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. He settles in along with his wife, Wendy (Shelley Duvall), and his son, Danny (Danny Lloyd), who is plagued by psychic premonitions. As Jack's writing goes nowhere and Danny's visions become more disturbing, Jack discovers the hotel's dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.",
  },
  {
    title: "The Shining 4",
    img: "/assets/images/cover_the_shining.webp",
    status: "Completed",
    rating: "4.5",
    genre: ["Action", "Fantasy"],
    desc: "Jack Torrance (Jack Nicholson) becomes winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. He settles in along with his wife, Wendy (Shelley Duvall), and his son, Danny (Danny Lloyd), who is plagued by psychic premonitions. As Jack's writing goes nowhere and Danny's visions become more disturbing, Jack discovers the hotel's dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.",
  },
  {
    title: "The Shining 5",
    img: "/assets/images/cover_the_shining.webp",
    status: "Ongoing",
    rating: "3.2",
    genre: ["Horror", "Mystery"],
    desc: "Jack Torrance (Jack Nicholson) becomes winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. He settles in along with his wife, Wendy (Shelley Duvall), and his son, Danny (Danny Lloyd), who is plagued by psychic premonitions. As Jack's writing goes nowhere and Danny's visions become more disturbing, Jack discovers the hotel's dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.",
  },
  {
    title: "The Shining 6",
    img: "/assets/images/cover_the_shining.webp",
    status: "Haitus",
    rating: "4.7",
    genre: ["Sci Fi", "Dystopian"],
    desc: "Jack Torrance (Jack Nicholson) becomes winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. He settles in along with his wife, Wendy (Shelley Duvall), and his son, Danny (Danny Lloyd), who is plagued by psychic premonitions. As Jack's writing goes nowhere and Danny's visions become more disturbing, Jack discovers the hotel's dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.",
  },
  {
    title: "The Shining 7",
    img: "/assets/images/cover_the_shining.webp",
    status: "Completed",
    rating: "4.5",
    genre: ["Action", "Fantasy"],
    desc: "Jack Torrance (Jack Nicholson) becomes winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. He settles in along with his wife, Wendy (Shelley Duvall), and his son, Danny (Danny Lloyd), who is plagued by psychic premonitions. As Jack's writing goes nowhere and Danny's visions become more disturbing, Jack discovers the hotel's dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.",
  },
  {
    title: "The Shining 8",
    img: "/assets/images/cover_the_shining.webp",
    status: "Ongoing",
    rating: "3.2",
    genre: ["Horror", "Mystery"],
    desc: "Jack Torrance (Jack Nicholson) becomes winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. He settles in along with his wife, Wendy (Shelley Duvall), and his son, Danny (Danny Lloyd), who is plagued by psychic premonitions. As Jack's writing goes nowhere and Danny's visions become more disturbing, Jack discovers the hotel's dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.",
  },
  {
    title: "The Shining 9",
    img: "/assets/images/cover_the_shining.webp",
    status: "Haitus",
    rating: "4.7",
    genre: ["Sci Fi", "Dystopian"],
    desc: "Jack Torrance (Jack Nicholson) becomes winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. He settles in along with his wife, Wendy (Shelley Duvall), and his son, Danny (Danny Lloyd), who is plagued by psychic premonitions. As Jack's writing goes nowhere and Danny's visions become more disturbing, Jack discovers the hotel's dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.",
  },
  {
    title: "The Shining 10",
    img: "/assets/images/cover_the_shining.webp",
    status: "Completed",
    rating: "4.5",
    genre: ["Action", "Fantasy"],
    desc: "Jack Torrance (Jack Nicholson) becomes winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. He settles in along with his wife, Wendy (Shelley Duvall), and his son, Danny (Danny Lloyd), who is plagued by psychic premonitions. As Jack's writing goes nowhere and Danny's visions become more disturbing, Jack discovers the hotel's dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.",
  },
  {
    title: "The Shining 11",
    img: "/assets/images/cover_the_shining.webp",
    status: "Ongoing",
    rating: "3.2",
    genre: ["Horror", "Mystery"],
    desc: "Jack Torrance (Jack Nicholson) becomes winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. He settles in along with his wife, Wendy (Shelley Duvall), and his son, Danny (Danny Lloyd), who is plagued by psychic premonitions. As Jack's writing goes nowhere and Danny's visions become more disturbing, Jack discovers the hotel's dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.",
  },
  {
    title: "The Shining 12",
    img: "/assets/images/cover_the_shining.webp",
    status: "Haitus",
    rating: "4.7",
    genre: ["Sci Fi", "Dystopian"],
    desc: "Jack Torrance (Jack Nicholson) becomes winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. He settles in along with his wife, Wendy (Shelley Duvall), and his son, Danny (Danny Lloyd), who is plagued by psychic premonitions. As Jack's writing goes nowhere and Danny's visions become more disturbing, Jack discovers the hotel's dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.",
  },
];

export { BOOKS_WITH_TAGS };
