const MY_NOVELS = [
  {
    title: "The Shining 1",
    img: "/assets/images/cover_the_shining.webp",
    status: "completed",
    last_chapter: "123",
    updated_on: "12/12/22",
    rating: "3.2",
  },
  {
    title: "The Shining 2",
    img: "/assets/images/the_shining.jpg",
    status: "haitus",
    last_chapter: "123",
    updated_on: "12/12/22",
    rating: "4.5",
  },
  {
    title: "The Shining 3",
    img: "/assets/images/cover_the_shining.webp",
    status: "ongoing",
    last_chapter: "123",
    updated_on: "12/12/22",
    rating: "4.5",
  },
  {
    title: "The Shining 4",
    img: "/assets/images/the_shining.jpg",
    status: "completed",
    last_chapter: "123",
    updated_on: "12/12/22",
    rating: "3.2",
  },
  {
    title: "The Shining 5",
    img: "/assets/images/cover_the_shining.webp",
    status: "haitus",
    last_chapter: "123",
    updated_on: "12/12/22",
    rating: "4.7",
  },
  {
    title: "The Shining 6",
    img: "/assets/images/the_shining.jpg",
    status: "ongoing",
    last_chapter: "123",
    updated_on: "12/12/22",
    rating: "3.2",
  },
  {
    title: "The Shining 7",
    img: "/assets/images/cover_the_shining.webp",
    status: "haitus",
    last_chapter: "123",
    updated_on: "12/12/22",
    rating: "4.7",
  },
];

export { MY_NOVELS };
