const NOVEL = {
  title: "The Shining",
  img: "/assets/images/cover_the_shining.webp",
  status: "Completed",
  author: "Stephen King",
  latestChapter: "20",
  recommendation: "overwhelmingly recommended",
  rating: "4.8",
  genre: ["Action", "Fantasy"],
  desc: "Jack Torrance (Jack Nicholson) becomes winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. He settles in along with his wife, Wendy (Shelley Duvall), and his son, Danny (Danny Lloyd), who is plagued by psychic premonitions. As Jack's writing goes nowhere and Danny's visions become more disturbing, Jack discovers the hotel's dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.",
  chapterList: [
    { id: "40", title: "The Boys" },
    { id: "39", title: "The Boys" },
    { id: "38", title: "The Boys" },
    { id: "37", title: "The Boys" },
    { id: "36", title: "The Boys" },
    { id: "35", title: "The Boys" },
    { id: "34", title: "The Boys" },
    { id: "33", title: "The Boys" },
    { id: "32", title: "The Boys" },
    { id: "31", title: "The Boys" },
    { id: "30", title: "The Boys" },
    { id: "29", title: "The Boys" },
    { id: "28", title: "The Boys" },
    { id: "27", title: "The Boys" },
    { id: "26", title: "The Boys" },
    { id: "25", title: "The Boys" },
    { id: "24", title: "The Boys" },
    { id: "23", title: "The Boys" },
    { id: "22", title: "The Boys" },
    { id: "21", title: "The Boys" },
    { id: "20", title: "The Boys" },
    { id: "19", title: "The Boys" },
    { id: "18", title: "The Boys" },
    { id: "17", title: "The Boys" },
    { id: "16", title: "The Boys" },
    { id: "15", title: "The Boys" },
    { id: "14", title: "The Boys" },
    { id: "13", title: "The Boys" },
    { id: "12", title: "The Boys" },
    { id: "11", title: "The Boys" },
    { id: "10", title: "The Boys" },
    { id: "9", title: "The Boys" },
    { id: "8", title: "The Boys" },
    { id: "7", title: "The Boys" },
    { id: "6", title: "The Boys" },
    { id: "5", title: "The Boys" },
    { id: "4", title: "The Boys" },
    { id: "3", title: "The Boys" },
    { id: "2", title: "The Boys" },
    { id: "1", title: "The Boys" },
  ],
};

export { NOVEL };
