const RECENTLY_UPDATED = [
  {
    title: "The Shining 1",
    img: "/assets/images/the_shining.jpg",
    chapter: "123",
    chapterTitle: "The Gift",
    author: "Stephen King",
    time: "1 hour ago",
  },
  {
    title: "The Shining 2",
    img: "/assets/images/the_shining.jpg",
    chapter: "123",
    chapterTitle: "The Gift",
    author: "Stephen King",
    time: "1 hour ago",
  },
  {
    title: "The Shining 3",
    img: "/assets/images/the_shining.jpg",
    chapter: "123",
    chapterTitle: "The Gift",
    author: "Stephen King",
    time: "1 hour ago",
  },
  {
    title: "The Shining 4",
    img: "/assets/images/the_shining.jpg",
    chapter: "123",
    chapterTitle: "The Gift",
    author: "Stephen King",
    time: "1 hour ago",
  },
  {
    title: "The Shining 5",
    img: "/assets/images/the_shining.jpg",
    chapter: "123",
    chapterTitle: "The Gift",
    author: "Stephen King",
    time: "1 hour ago",
  },
  {
    title: "The Shining 6",
    img: "/assets/images/the_shining.jpg",
    chapter: "123",
    chapterTitle: "The Gift",
    author: "Stephen King",
    time: "1 hour ago",
  },
  {
    title: "The Shining 7",
    img: "/assets/images/the_shining.jpg",
    chapter: "123",
    chapterTitle: "The Gift",
    author: "Stephen King",
    time: "1 hour ago",
  },
  {
    title: "The Shining 8",
    img: "/assets/images/the_shining.jpg",
    chapter: "123",
    chapterTitle: "The Gift",
    author: "Stephen King",
    time: "1 hour ago",
  },
  {
    title: "The Shining 9",
    img: "/assets/images/the_shining.jpg",
    chapter: "123",
    chapterTitle: "The Gift",
    author: "Stephen King",
    time: "1 hour ago",
  },
];

export { RECENTLY_UPDATED };
